apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: "anchaleev/nodendb:image_version"
        ports:
        - containerPort: 8080
      hostAliases:
      - ip: "34.30.100.220"
        hostnames:
        - "postgresql"    

          
